### ISSUE TITLE
Add support for `.treerc` file

### ISSUE THREAD

**Issue by alex-oser** [structure-codes/cli#3]
What language should the config file be?

# yaml
```yaml
ignored:
  - node_modules
  - .git
  - dist
editor: code
```
# json
```json
{
  "ignored": [
    "node_modules",
    ".git",
    "dist"
  ],
  "editor": "code"
}
```

# jsonc
```jsonc
{
  "ignored": [
    "node_modules",
    ".git",
    "dist"
  ],
  // select which editor you prefer
  "editor": "code"
}
```
